window.RAW_DATA = [
  // #region WEAPONS
  // ── 1H AXES ──────────────────────────────────
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Normal',n:'The Gnasher',b:'Hand Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Normal',n:'Deathspade',b:'Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Normal',n:'Bladebone',b:'Double Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Normal',n:'Skull Splitter',b:'Military Pick'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Normal',n:'Rakescar',b:'War Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Exceptional',n:'Coldkill',b:'Hatchet'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Exceptional',n:'Butcher\'s Pupil',b:'Cleaver'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Exceptional',n:'Islestrike',b:'Twin Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Exceptional',n:'Pompeii\'s Wrath',b:'Crowbill'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Exceptional',n:'Guardian Naga',b:'Naga'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Elite',n:'Razor\'s Edge',b:'Tomahawk'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Elite',n:'Rune Master',b:'Ettin Axe'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Elite',n:'Cranebeak',b:'War Spike'},
    {t:'u',tab:'weapons',c:'1H Axes',tier:'Elite',n:'Death Cleaver',b:'Berserker Axe'},
    // ── 2H AXES ──────────────────────────────────
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Normal',n:'Axe of Fechmar',b:'Large Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Normal',n:'Goreshovel',b:'Broad Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Normal',n:'The Chieftain',b:'Battle Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Normal',n:'Brainhew',b:'Great Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Normal',n:'Humongous',b:'Giant Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Exceptional',n:'Warlord\'s Trust',b:'Military Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Exceptional',n:'Spellsteel',b:'Bearded Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Exceptional',n:'Stormrider',b:'Tabar'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Exceptional',n:'Boneslayer Blade',b:'Gothic Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Exceptional',n:'The Minotaur',b:'Ancient Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Elite',n:'Ethereal Edge',b:'Silver-Edged Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Elite',n:'Hellslayer',b:'Decapitator'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Elite',n:'Messerschmidt\'s Reaver',b:'Champion Axe'},
    {t:'u',tab:'weapons',c:'2H Axes',tier:'Elite',n:'Executioner\'s Justice',b:'Glorious Axe'},
    // ── 1H SWORDS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Rixot\'s Keen',b:'Short Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Blood Crescent',b:'Scimitar'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Skewer of Krintiz',b:'Sabre'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Gleamscythe',b:'Falchion'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Griswold\'s Edge',b:'Broad Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Hellplague',b:'Long Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Normal',n:'Culwen\'s Point',b:'War Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Bloodletter',b:'Gladius'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Coldsteel Eye',b:'Cutlass'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Hexfire',b:'Shamshir'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Blade of Ali Baba',b:'Tulwar'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Ginther\'s Rift',b:'Dimensional Blade'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Headstriker',b:'Battle Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'Plague Bearer',b:'Rune Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Exceptional',n:'The Atlantean',b:'Ancient Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Djinn Slayer',b:'Ataghan'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Bloodmoon',b:'Elegant Blade'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Lightsabre',b:'Phase Blade'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Azurewrath',b:'Phase Blade'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Frostwind',b:'Cryptic Sword'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Hadriel\'s Hand',b:'Conquest Sword',src:'DClone'},
    {t:'u',tab:'weapons',c:'1H Swords',tier:'Elite',n:'Armageddon\'s Blade',b:'Phase Blade',src:'Charsi'},
    // ── 2H SWORDS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'Shadowfang',b:'Two-Handed Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'Soulflay',b:'Claymore'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'Kinemil\'s Awl',b:'Giant Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'Blacktongue',b:'Bastard Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'Ripsaw',b:'Flamberge'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Normal',n:'The Patriarch',b:'Great Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'Crainte Vomir',b:'Espandon'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'Bing Sz Wang',b:'Dacian Falx'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'The Vile Husk',b:'Tusk Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'Cloudcrack',b:'Gothic Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'Todesfaelle Flamme',b:'Zweihander'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Exceptional',n:'Swordguard',b:'Executioner Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Elite',n:'Leoric\'s Mithril Bane',b:'Highland Blade'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Elite',n:'Flamebellow',b:'Balrog Blade'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Elite',n:'Doombringer',b:'Champion Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Elite',n:'Odium',b:'Colossus Sword'},
    {t:'u',tab:'weapons',c:'2H Swords',tier:'Elite',n:'The Grandfather',b:'Colossus Blade'},
    // ── 1H MACES ──────────────────────────────────
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'Felloak',b:'Club'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'Stoutnail',b:'Spiked Club'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'Crushflange',b:'Mace'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'Bloodrise',b:'Morning Star'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'The General\'s Tan Do Li Ga',b:'Flail'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Normal',n:'Ironstone',b:'War Hammer'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Dark Clan Crusher',b:'Cudgel'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Fleshrender',b:'Barbed Club'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Sureshrill Frost',b:'Flanged Mace'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Moonfall',b:'Jagged Star'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Baezil\'s Vortex',b:'Knout'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Exceptional',n:'Earthshaker',b:'Battle Hammer'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Nord\'s Tenderizer',b:'Truncheon'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Demon Limb',b:'Tyrant Club'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Baranar\'s Star',b:'Devil Star'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Horizon\'s Tornado',b:'Scourge'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Stormlash',b:'Scourge'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Stone Crusher',b:'Legendary Mallet'},
    {t:'u',tab:'weapons',c:'1H Maces',tier:'Elite',n:'Schaefer\'s Hammer',b:'Legendary Mallet'},
    // ── 2H MACES ──────────────────────────────────
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Normal',n:'Bonesnap',b:'Maul'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Normal',n:'Steeldriver',b:'Great Maul'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Exceptional',n:'Bloodtree Stump',b:'War Club'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Exceptional',n:'The Gavel of Pain',b:'Martel de Fer'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Elite',n:'Windhammer',b:'Ogre Maul'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Elite',n:'Earth Shifter',b:'Thunder Maul'},
    {t:'u',tab:'weapons',c:'2H Maces',tier:'Elite',n:'The Cranium Basher',b:'Thunder Maul'},
    // ── DAGGERS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Daggers',tier:'Normal',n:'Gull',b:'Dagger'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Normal',n:'The Diggler',b:'Dirk'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Normal',n:'The Jade Tan Do',b:'Kris'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Normal',n:'Spectral Shard',b:'Blade'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Exceptional',n:'Spineripper',b:'Poignard'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Exceptional',n:'Heart Carver',b:'Rondel'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Exceptional',n:'Blackbog\'s Sharp',b:'Cinquedeas'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Exceptional',n:'Stormspike',b:'Stiletto'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Elite',n:'Wizardspike',b:'Bone Knife'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Elite',n:'Shatterblade',b:'Mithril Point'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Elite',n:'Fleshripper',b:'Fanged Knife'},
    {t:'u',tab:'weapons',c:'Daggers',tier:'Elite',n:'Ghostflame',b:'Legend Spike'},
    // ── SPEARS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Spears',tier:'Normal',n:'The Dragon Chang',b:'Spear'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Normal',n:'Razortine',b:'Trident'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Normal',n:'Bloodthief',b:'Brandistock'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Normal',n:'Lance of Yaggai',b:'Spetum'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Normal',n:'The Tannr Gorerod',b:'Pike'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'The Impaler',b:'War Spear'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'Kelpie Snare',b:'Fuscina'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'Soulfeast Tine',b:'War Fork'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'Hone Sundan',b:'Yari'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'Spire of Honor',b:'Lance'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Exceptional',n:'Lycander\'s Flank',b:'Ceremonial Pike'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Arioc\'s Needle',b:'Hyperion Spear'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Viperfork',b:'Mancatcher'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Uldyssian\'s Awakening',b:'Ghost Spear'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Steel Pillar',b:'War Pike'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Stoneraven',b:'Matriarchal Spear'},
    {t:'u',tab:'weapons',c:'Spears',tier:'Elite',n:'Zerae\'s Resolve',b:'Matriarchal Pike'},
    // ── POLEARMS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'Dimoak\'s Hew',b:'Bardiche'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'Steelgoad',b:'Voulge'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'Soul Harvest',b:'Scythe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'The Battlebranch',b:'Poleaxe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'Woestave',b:'Halberd'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Normal',n:'The Grim Reaper',b:'War Scythe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'The Meat Scraper',b:'Lochaber Axe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'Blackleach Blade',b:'Bill'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'Athena\'s Wrath',b:'Battle Scythe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'Pierre Tombale Couant',b:'Partizan'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'Husoldal Evo',b:'Bec-De-Corbin'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Exceptional',n:'Grim\'s Burning Dead',b:'Grim Scythe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Elite',n:'Bonehew',b:'Ogre Axe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Elite',n:'The Reaper\'s Toll',b:'Thresher'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Elite',n:'Giant Maimer',b:'Colossus Voulge'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Elite',n:'Tomb Reaver',b:'Cryptic Axe'},
    {t:'u',tab:'weapons',c:'Polearms',tier:'Elite',n:'Stormspire',b:'Giant Thresher'},
    // ── BOWS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Pluckeye',b:'Short Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Witherstring',b:'Hunter\'s Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Raven Claw',b:'Long Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Rogue\'s Bow',b:'Composite Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Stormstrike',b:'Short Battle Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Wizendraw',b:'Long Battle Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Hellclap',b:'Short War Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Normal',n:'Blastbark',b:'Long War Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Skystrike',b:'Edge Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Riphook',b:'Razor Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Kuko Shakaku',b:'Cedar Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Endlesshail',b:'Double Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Witchwild String',b:'Short Siege Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Cliffkiller',b:'Large Siege Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Magewrath',b:'Rune Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Goldstrike Arch',b:'Gothic Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Exceptional',n:'Lycander\'s Aim',b:'Ceremonial Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Crackleshot',b:'Blade Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Eaglehorn',b:'Crusader Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Widowmaker',b:'Ward Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Windforce',b:'Hydra Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Blood Raven\'s Charge',b:'Matriarchal Bow'},
    {t:'u',tab:'weapons',c:'Bows',tier:'Elite',n:'Ebonbane',b:'Grand Matron Bow'},
    // ── CROSSBOWS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Normal',n:'Leadcrow',b:'Light Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Normal',n:'Ichorsting',b:'Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Normal',n:'Hellcast',b:'Heavy Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Normal',n:'Doomslinger',b:'Repeating Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Exceptional',n:'Langer Briser',b:'Arbalest'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Exceptional',n:'Pus Spitter',b:'Siege Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Exceptional',n:'Buriza-Do Kyanon',b:'Ballista'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Exceptional',n:'Demon Machine',b:'Chu-Ko-Nu'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Elite',n:'Gut Siphon',b:'Demon Crossbow'},
    {t:'u',tab:'weapons',c:'Crossbows',tier:'Elite',n:'Hellrack',b:'Colossus Crossbow'},
    // ── JAVELINS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Javelins',tier:'Normal',n:'True Silver',b:'Maiden Javelin'},
    {t:'u',tab:'weapons',c:'Javelins',tier:'Exceptional',n:'Titan\'s Revenge',b:'Ceremonial Javelin'},
    {t:'u',tab:'weapons',c:'Javelins',tier:'Elite',n:'Thunderstroke',b:'Matriarchal Javelin'},
    {t:'u',tab:'weapons',c:'Javelins',tier:'Elite',n:'Demon\'s Arch',b:'Balrog Spear'},
    {t:'u',tab:'weapons',c:'Javelins',tier:'Elite',n:'Wraith Flight',b:'Ghost Glaive'},
    {t:'u',tab:'weapons',c:'Javelins',tier:'Elite',n:'Gargoyle\'s Bite',b:'Winged Harpoon'},
    // ── THROWING ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Throwing',tier:'Exceptional',n:'Deathbit',b:'Battle Dart'},
    {t:'u',tab:'weapons',c:'Throwing',tier:'Exceptional',n:'The Scalper',b:'Francisca'},
    {t:'u',tab:'weapons',c:'Throwing',tier:'Exceptional',n:'Achilles Strike',b:'Hurlbat'},
    {t:'u',tab:'weapons',c:'Throwing',tier:'Elite',n:'Gimmershred',b:'Flying Axe'},
    {t:'u',tab:'weapons',c:'Throwing',tier:'Elite',n:'Warshrike',b:'Winged Knife'},
    {t:'u',tab:'weapons',c:'Throwing',tier:'Elite',n:'Lacerator',b:'Winged Axe'},
    // ── STAVES ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Staves',tier:'Normal',n:'Bane Ash',b:'Short Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Normal',n:'Serpent Lord',b:'Long Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Normal',n:'Spire of Lazarus',b:'Gnarled Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Normal',n:'The Salamander',b:'Battle Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Normal',n:'The Iron Jang Bong',b:'War Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Exceptional',n:'Razorswitch',b:'Jo Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Exceptional',n:'Ribcracker',b:'Quarterstaff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Exceptional',n:'Chromatic Ire',b:'Cedar Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Exceptional',n:'Warpspear',b:'Gothic Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Exceptional',n:'Skull Collector',b:'Rune Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Elite',n:'Brimstone Rain',b:'Shillelagh'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Elite',n:'Ondal\'s Wisdom',b:'Elder Staff'},
    {t:'u',tab:'weapons',c:'Staves',tier:'Elite',n:'Mang Song\'s Lesson',b:'Archon Staff'},
    // ── WANDS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Wands',tier:'Normal',n:'Torch of Iro',b:'Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Normal',n:'Maelstrom',b:'Yew Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Normal',n:'Gravenspine',b:'Bone Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Normal',n:'Ume\'s Lament',b:'Grim Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Exceptional',n:'Suicide Branch',b:'Burnt Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Exceptional',n:'Carin Shard',b:'Petrified Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Exceptional',n:'Arm of King Leoric',b:'Tomb Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Exceptional',n:'Blackhand Key',b:'Grave Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Elite',n:'Nethercrux',b:'Ghost Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Elite',n:'Boneshade',b:'Lich Wand'},
    {t:'u',tab:'weapons',c:'Wands',tier:'Elite',n:'Death\'s Web',b:'Unearthed Wand'},
    // ── SCEPTERS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Scepters',tier:'Normal',n:'Knell Striker',b:'Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Normal',n:'Rusthandle',b:'Grand Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Normal',n:'Stormeye',b:'War Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Exceptional',n:'Zakarum\'s Hand',b:'Rune Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Exceptional',n:'The Fetid Sprinkler',b:'Holy Water Sprinkler'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Exceptional',n:'Hand of Blessed Light',b:'Divine Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Elite',n:'Heaven\'s Light',b:'Mighty Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Elite',n:'The Redeemer',b:'Mighty Scepter'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Elite',n:'Akarat\'s Devotion',b:'Seraph Rod'},
    {t:'u',tab:'weapons',c:'Scepters',tier:'Elite',n:'Astreon\'s Iron Ward',b:'Caduceus'},
    // ── CLAWS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Claws',tier:'Exceptional',n:'Mage Slayer',b:'Quhab'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Exceptional',n:'Bartuc\'s Cut-Throat',b:'Greater Talons'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Stalker\'s Cull',b:'Runic Talons'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Jade Talon',b:'Wrist Sword'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Firelizard\'s Talons',b:'Feral Claws'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Shadow Killer',b:'Battle Cestus'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Whispering Mirage',b:'War Fist'},
    {t:'u',tab:'weapons',c:'Claws',tier:'Elite',n:'Aidan\'s Scar',b:'Scissors Suwayyah',src:'DClone'},
    // ── ORBS ──────────────────────────────────
    {t:'u',tab:'weapons',c:'Orbs',tier:'Exceptional',n:'Tempest',b:'Glowing Orb'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Exceptional',n:'Skorn',b:'Crystalline Globe'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Exceptional',n:'The Oculus',b:'Swirling Crystal'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Elite',n:'Embersworn',b:'Demon Heart'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Elite',n:'Skyfall',b:'Vortex Orb'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Elite',n:'Eschuta\'s Temper',b:'Eldritch Orb'},
    {t:'u',tab:'weapons',c:'Orbs',tier:'Elite',n:'Death\'s Fathom',b:'Dimensional Shard'},
  // #endregion,

  // #region ARMOR
  // ── HELMS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Biggin\'s Bonnet',b:'Cap'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Tarnhelm',b:'Skull Cap'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Coif of Glory',b:'Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Duskdeep',b:'Full Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'The Face of Horror',b:'Mask'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Wormskull',b:'Bone Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Howltusk',b:'Great Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Normal',n:'Undead Crown',b:'Crown'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Peasant Crown',b:'War Hat'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Rockstopper',b:'Sallet'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Stealskull',b:'Casque'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Darksight Helm',b:'Basinet'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Blackhorn\'s Face',b:'Death Mask'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Vampire Gaze',b:'Grim Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Valkyrie Wing',b:'Winged Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Crown of Thieves',b:'Grand Crown'},
    {t:'u',tab:'armor',c:'Helms',tier:'Exceptional',n:'Kira\'s Guardian',b:'Tiara'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Sage\'s Defiance',b:'Giant Conch'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Harlequin Crest',b:'Shako'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Steel Shade',b:'Armet'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Andariel\'s Visage',b:'Demonhead'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Giant Skull',b:'Bone Visage'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Veil of Steel',b:'Spired Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Nightwing\'s Veil',b:'Spired Helm'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Crown of Ages',b:'Corona'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Overlord\'s Helm',b:'Bone Visage',src:'DClone'},
    {t:'u',tab:'armor',c:'Helms',tier:'Elite',n:'Griffon\'s Eye',b:'Diadem'},
     // ── BODY ARMOR ──────────────────────────────────
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Greyform',b:'Quilted Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Blinkbat\'s Form',b:'Leather Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'The Centurion',b:'Hard Leather Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Twitchthroe',b:'Studded Leather'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Darkglow',b:'Ring Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Hawkmail',b:'Scale Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Sparking Mail',b:'Chain Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Venom Ward',b:'Breast Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Iceblink',b:'Splint Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Boneflesh',b:'Plate Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Rockfleece',b:'Field Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Rattlecage',b:'Gothic Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Heavenly Garb',b:'Light Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Goldskin',b:'Full Plate Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Normal',n:'Silks of the Victor',b:'Ancient Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Spirit Shroud',b:'Ghost Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Skin of the Vipermagi',b:'Serpentskin Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Skin of the Flayed One',b:'Demonhide Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Iron Pelt',b:'Trellised Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Spirit Forge',b:'Linked Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Crow Caw',b:'Tigulated Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Shaftstop',b:'Mesh Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Duriel\'s Shell',b:'Cuirass'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Skullder\'s Ire',b:'Russet Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Guardian Angel',b:'Templar Coat'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Toothrow',b:'Sharktooth Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Atma\'s Wail',b:'Embossed Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Que-Hegan\'s Wisdom',b:'Mage Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Black Hades',b:'Chaos Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Exceptional',n:'Corpsemourn',b:'Ornate Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Ormus\' Robes',b:'Dusk Shroud'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'The Gladiator\'s Bane',b:'Wire Fleece'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Wraithskin',b:'Diamond Mail'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Arkaine\'s Valor',b:'Balrog Skin'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Leviathan',b:'Kraken Shell'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Purgatory',b:'Archon Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Steel Carapace',b:'Shadow Plate'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Templar\'s Might',b:'Sacred Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Tyrael\'s Might',b:'Sacred Armor'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Dark Abyss',b:'Lacquered Plate',src:'DClone'},
    {t:'u',tab:'armor',c:'Body Armor',tier:'Elite',n:'Cage of the Unsullied',b:'Boneweave',src:'Rathma'},
    // ── SHIELDS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Pelta Lunata',b:'Buckler'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Umbral Disk',b:'Small Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Stormguild',b:'Large Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Swordback Hold',b:'Spiked Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Steelclash',b:'Kite Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Wall of the Eyeless',b:'Bone Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'Bverrit Keep',b:'Tower Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Normal',n:'The Ward',b:'Gothic Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Visceratuant',b:'Defender'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Moser\'s Blessed Circle',b:'Round Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Stormchaser',b:'Scutum'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Lance Guard',b:'Barbed Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Tiamat\'s Rebuke',b:'Dragon Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Lidless Wall',b:'Grim Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Gerke\'s Sanctuary',b:'Pavise'},
    {t:'u',tab:'armor',c:'Shields',tier:'Exceptional',n:'Radament\'s Sphere',b:'Ancient Shield'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Blackoak Shield',b:'Luna'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Twilight\'s Reflection',b:'Hyperion'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Spike Thorn',b:'Blade Barrier'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Stormshield',b:'Monarch'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Head Hunter\'s Glory',b:'Troll Nest'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Medusa\'s Gaze',b:'Aegis'},
    {t:'u',tab:'armor',c:'Shields',tier:'Elite',n:'Spirit Ward',b:'Ward'},
    // ── BELTS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Belts',tier:'Normal',n:'Lenymo',b:'Sash'},
    {t:'u',tab:'armor',c:'Belts',tier:'Normal',n:'Snakecord',b:'Light Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Normal',n:'Nightsmoke',b:'Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Normal',n:'Goldwrap',b:'Heavy Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Normal',n:'Bladebuckle',b:'Plated Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Exceptional',n:'String of Ears',b:'Demonhide Sash'},
    {t:'u',tab:'armor',c:'Belts',tier:'Exceptional',n:'Razortail',b:'Sharkskin Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Exceptional',n:'Gloom\'s Trap',b:'Mesh Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Exceptional',n:'Snowclash',b:'Battle Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Exceptional',n:'Thundergod\'s Vigor',b:'War Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Elite',n:'Arachnid Mesh',b:'Spiderweb Sash'},
    {t:'u',tab:'armor',c:'Belts',tier:'Elite',n:'Nosferatu\'s Coil',b:'Vampirefang Belt'},
    {t:'u',tab:'armor',c:'Belts',tier:'Elite',n:'Verdungo\'s Hearty Cord',b:'Mithril Coil'},
    {t:'u',tab:'armor',c:'Belts',tier:'Elite',n:'Siggard\'s Staunch',b:'Colossus Girdle'},
    {t:'u',tab:'armor',c:'Belts',tier:'Elite',n:'Band of Skulls',b:'Troll Belt',src:'Rathma'},
    // ── QUIVERS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Quivers',tier:'Normal',n:'Balefire',b:'Blunt Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Exceptional',n:'Swiftwind Needle',b:'Sharp Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Exceptional',n:'Tombsong',b:'Sharp Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Aetherwing',b:'Razor Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Basilisk\'s Quill',b:'Razor Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Doom\'s Finger',b:'Razor Arrows'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Normal',n:'Ramfodder',b:'Light Bolts'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Exceptional',n:'Anvilguard Strap',b:'Heavy Bolts'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Exceptional',n:'Shatterhead',b:'Heavy Bolts'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Abyssal Ward',b:'War Bolts'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Bannerlord\'s Call',b:'War Bolts'},
    {t:'u',tab:'armor',c:'Quivers',tier:'Elite',n:'Frozen Sorrow',b:'War Bolts'},
    // ── BOOTS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Boots',tier:'Normal',n:'Hotspur',b:'Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Normal',n:'Gorefoot',b:'Heavy Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Normal',n:'Treads of Cthon',b:'Chain Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Normal',n:'Goblin Toe',b:'Light Plated Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Normal',n:'Tearhaunch',b:'Greaves'},
    {t:'u',tab:'armor',c:'Boots',tier:'Exceptional',n:'Infernostride',b:'Demonhide Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Exceptional',n:'Waterwalk',b:'Sharkskin Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Exceptional',n:'Silkweave',b:'Mesh Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Exceptional',n:'War Traveler',b:'Battle Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Exceptional',n:'Gore Rider',b:'War Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Elite',n:'Merman\'s Sprocket',b:'Wyrmhide Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Elite',n:'Sandstorm Trek',b:'Scarabshell Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Elite',n:'Marrowwalk',b:'Boneweave Boots'},
    {t:'u',tab:'armor',c:'Boots',tier:'Elite',n:'Shadow Dancer',b:'Myrmidon Greaves'},
    {t:'u',tab:'armor',c:'Boots',tier:'Elite',n:'Itherael\'s Path',b:'Mirrored Boots',src:'DClone'},
    // ── GLOVES ──────────────────────────────────
    {t:'u',tab:'armor',c:'Gloves',tier:'Normal',n:'The Hand of Broc',b:'Leather Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Normal',n:'Bloodfist',b:'Heavy Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Normal',n:'Chance Guards',b:'Chain Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Normal',n:'Magefist',b:'Light Gauntlets'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Normal',n:'Frostburn',b:'Gauntlets'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Exceptional',n:'Venom Grip',b:'Demonhide Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Exceptional',n:'Gravepalm',b:'Sharkskin Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Exceptional',n:'Ghoulhide',b:'Heavy Bracers'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Exceptional',n:'Lava Gout',b:'Battle Gauntlets'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Exceptional',n:'Hellmouth',b:'War Gauntlets'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Elite',n:'Titan\'s Grip',b:'Bramble Mitts'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Elite',n:'Dracul\'s Grasp',b:'Vampirebone Gloves'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Elite',n:'Soul Drainer',b:'Vambraces'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Elite',n:'Occultist',b:'Crusader Gauntlets'},
    {t:'u',tab:'armor',c:'Gloves',tier:'Elite',n:'Steelrend',b:'Ogre Gauntlets'},
    // ── PALADIN SHIELDS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Normal',n:'Sankekur\'s Fall',b:'Heraldic Shield'},
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Exceptional',n:'Herald of Zakarum',b:'Gilded Shield'},
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Elite',n:'Ephemeral',b:'Sacred Targe'},
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Elite',n:'Alma Negra',b:'Sacred Rondache'},
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Elite',n:'Dragonscale',b:'Zakarum Shield'},
    {t:'u',tab:'armor',c:'Paladin Shields',tier:'Elite',n:'Skywarden',b:'Vortex Shield'},
    // ── NECROMANCER HEADS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Exceptional',n:'Kalan\'s Legacy',b:'Mummified Trophy'},
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Exceptional',n:'Homunculus',b:'Hierophant Trophy'},
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Elite',n:'Boneflame',b:'Succubus Skull'},
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Elite',n:'Darkforce Spawn',b:'Bloodlord Skull'},
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Elite',n:'Sacred Totem',b:'Hellspawn Skull'},
    {t:'u',tab:'armor',c:'Necromancer Heads',tier:'Elite',n:'Martyrdom',b:'Overseer Skull'},
    // ── BARBARIAN HELMS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Exceptional',n:'Cyclopean Roar',b:'Jawbone Visor'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Exceptional',n:'Wildspeaker',b:'Lion Helm'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Exceptional',n:'Arreat\'s Face',b:'Slayer Guard'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Elite',n:'Wolfhowl',b:'Fury Visor'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Elite',n:'Demonhorn\'s Edge',b:'Destroyer Helm'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Elite',n:'Halaberd\'s Reign',b:'Conqueror Crown'},
    {t:'u',tab:'armor',c:'Barbarian Helms',tier:'Elite',n:'Raekor\'s Virtue',b:'Guardian Crown'},
    // ── DRUID PELTS ──────────────────────────────────
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Normal',n:'Quetzalcoatl',b:'Hawk Helm'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Exceptional',n:'Fenris',b:'Alpha Helm'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Exceptional',n:'Jalal\'s Mane',b:'Totemic Mask'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Elite',n:'Cerebus\' Bite',b:'Blood Spirit'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Elite',n:'Denmother',b:'Sun Spirit'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Elite',n:'Ravenlore',b:'Sky Spirit'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Elite',n:'Spirit Keeper',b:'Earth Spirit'},
    {t:'u',tab:'armor',c:'Druid Pelts',tier:'Elite',n:'Ursa\'s Nightmare',b:'Dream Spirit'},
  // #endregion,

  // #region JEWELRY
  // -- RINGS ----------------------------------
    {t:'u',tab:'jewelry',c:'Rings',n:'Nagelring',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Manald Heal',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'The Stone of Jordan',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Dwarf Star',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Raven Frost',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Bul-Kathos\' Wedding Band',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Carrion Wind',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Nature\'s Peace',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Wisp Projector',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Constricting Loop',b:'Ring'},
    {t:'u',tab:'jewelry',c:'Rings',n:'Kadala\'s Heirloom',b:'Ring'},
    // -- AMULETS ----------------------------------
    {t:'u',tab:'jewelry',c:'Amulets',n:'Nokozan Relic',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'The Eye of Etlich',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'The Mahim-Oak Curio',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Saracen\'s Chance',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Crescent Moon',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'The Cat\'s Eye',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Atma\'s Scarab',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Highlord\'s Wrath',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'The Rising Sun',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Seraph\'s Hymn',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Mara\'s Kaleidoscope',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'Metalgrid',b:'Amulet'},
    {t:'u',tab:'jewelry',c:'Amulets',n:'The Third Eye',b:'Amulet',src:'Rathma'},
  // #endregion,

  // #region SET ITEMS
  // ── ARCTIC GEAR ──
    {t:'s',tab:'sets',c:'Arctic Gear',tier:'Normal',n:'Arctic Furs',b:'Quilted Armor'},
    {t:'s',tab:'sets',c:'Arctic Gear',tier:'Normal',n:'Arctic Binding',b:'Light Belt'},
    {t:'s',tab:'sets',c:'Arctic Gear',tier:'Normal',n:'Arctic Mitts',b:'Light Gauntlets'},
    {t:'s',tab:'sets',c:'Arctic Gear',tier:'Normal',n:'Arctic Horn',b:'Short War Bow'},
    // ── HSARUS' DEFENSE ──
    {t:'s',tab:'sets',c:'Hsarus\' Defense',tier:'Normal',n:'Hsarus\' Iron Heel',b:'Chain Boots'},
    {t:'s',tab:'sets',c:'Hsarus\' Defense',tier:'Normal',n:'Hsarus\' Iron Stay',b:'Belt'},
    {t:'s',tab:'sets',c:'Hsarus\' Defense',tier:'Normal',n:'Hsarus\' Iron Fist',b:'Buckler'},
    // ── BERSERKER'S ARSENAL ──
    {t:'s',tab:'sets',c:'Berserker\'s Arsenal',tier:'Normal',n:'Berserker\'s Headgear',b:'Helm'},
    {t:'s',tab:'sets',c:'Berserker\'s Arsenal',tier:'Normal',n:'Berserker\'s Hauberk',b:'Splint Mail'},
    {t:'s',tab:'sets',c:'Berserker\'s Arsenal',tier:'Normal',n:'Berserker\'s Hatchet',b:'Double Axe'},
    // ── CLEGLAW'S BRACE ──
    {t:'s',tab:'sets',c:'Cleglaw\'s Brace',tier:'Normal',n:'Cleglaw\'s Pincers',b:'Chain Gloves'},
    {t:'s',tab:'sets',c:'Cleglaw\'s Brace',tier:'Normal',n:'Cleglaw\'s Claw',b:'Small Shield'},
    {t:'s',tab:'sets',c:'Cleglaw\'s Brace',tier:'Normal',n:'Cleglaw\'s Tooth',b:'Long Sword'},
    // ── INFERNAL TOOLS ──
    {t:'s',tab:'sets',c:'Infernal Tools',tier:'Normal',n:'Infernal Cranium',b:'Cap'},
    {t:'s',tab:'sets',c:'Infernal Tools',tier:'Normal',n:'Infernal Sign',b:'Heavy Belt'},
    {t:'s',tab:'sets',c:'Infernal Tools',tier:'Normal',n:'Infernal Spire (Infernal Torch)',b:'Dagger'},
    // ── DEATH'S DISGUISE ──
    {t:'s',tab:'sets',c:'Death\'s Disguise',tier:'Normal',n:'Death\'s Guard',b:'Sash'},
    {t:'s',tab:'sets',c:'Death\'s Disguise',tier:'Normal',n:'Death\'s Hand',b:'Leather Gloves'},
    {t:'s',tab:'sets',c:'Death\'s Disguise',tier:'Normal',n:'Death\'s Touch',b:'War Sword'},
    // ── SIGON'S COMPLETE STEEL ──
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Visor',b:'Great Helm'},
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Shelter',b:'Gothic Plate'},
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Sabot',b:'Greaves'},
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Wrap',b:'Plated Belt'},
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Gage',b:'Gauntlets'},
    {t:'s',tab:'sets',c:'Sigon\'s Complete Steel',tier:'Normal',n:'Sigon\'s Guard',b:'Tower Shield'},
    // ── ISENHART'S ARMORY ──
    {t:'s',tab:'sets',c:'Isenhart\'s Armory',tier:'Normal',n:'Isenhart\'s Horns',b:'Full Helm'},
    {t:'s',tab:'sets',c:'Isenhart\'s Armory',tier:'Normal',n:'Isenhart\'s Case',b:'Breast Plate'},
    {t:'s',tab:'sets',c:'Isenhart\'s Armory',tier:'Normal',n:'Isenhart\'s Parry',b:'Gothic Shield'},
    {t:'s',tab:'sets',c:'Isenhart\'s Armory',tier:'Normal',n:'Isenhart\'s Lightbrand',b:'Broad Sword'},
    // ── CIVERB'S VESTMENTS ──
    {t:'s',tab:'sets',c:'Civerb\'s Vestments',tier:'Normal',n:'Civerb\'s Ward',b:'Large Shield'},
    {t:'s',tab:'sets',c:'Civerb\'s Vestments',tier:'Normal',n:'Civerb\'s Cudgel',b:'Grand Scepter'},
    {t:'s',tab:'sets',c:'Civerb\'s Vestments',n:'Civerb\'s Icon',b:'Amulet'},
    // ── CATHAN'S TRAPS ──
    {t:'s',tab:'sets',c:'Cathan\'s Traps',tier:'Normal',n:'Cathan\'s Visage',b:'Mask'},
    {t:'s',tab:'sets',c:'Cathan\'s Traps',tier:'Normal',n:'Cathan\'s Mesh',b:'Chain Mail'},
    {t:'s',tab:'sets',c:'Cathan\'s Traps',tier:'Normal',n:'Cathan\'s Rule',b:'Battle Staff'},
    {t:'s',tab:'sets',c:'Cathan\'s Traps',n:'Cathan\'s Sigil',b:'Amulet'},
    {t:'s',tab:'sets',c:'Cathan\'s Traps',n:'Cathan\'s Seal',b:'Ring'},
    // ── ANGELIC RAIMENT ──
    {t:'s',tab:'sets',c:'Angelic Raiment',tier:'Normal',n:'Angelic Mantle',b:'Ring Mail'},
    {t:'s',tab:'sets',c:'Angelic Raiment',tier:'Normal',n:'Angelic Sickle',b:'Sabre'},
    {t:'s',tab:'sets',c:'Angelic Raiment',n:'Angelic Wings',b:'Amulet'},
    {t:'s',tab:'sets',c:'Angelic Raiment',n:'Angelic Halo',b:'Ring'},
    // ── VIDALA'S RIG ──
    {t:'s',tab:'sets',c:'Vidala\'s Rig',tier:'Normal',n:'Vidala\'s Ambush',b:'Leather Armor'},
    {t:'s',tab:'sets',c:'Vidala\'s Rig',tier:'Normal',n:'Vidala\'s Fetlock',b:'Light Plated Boots'},
    {t:'s',tab:'sets',c:'Vidala\'s Rig',tier:'Normal',n:'Vidala\'s Barb',b:'Long Battle Bow'},
    {t:'s',tab:'sets',c:'Vidala\'s Rig',n:'Vidala\'s Snare',b:'Amulet'},
    // ── ARCANNA'S TRICKS ──
    {t:'s',tab:'sets',c:'Arcanna\'s Tricks',tier:'Normal',n:'Arcanna\'s Head',b:'Skull Cap'},
    {t:'s',tab:'sets',c:'Arcanna\'s Tricks',tier:'Normal',n:'Arcanna\'s Flesh',b:'Light Plate'},
    {t:'s',tab:'sets',c:'Arcanna\'s Tricks',tier:'Normal',n:'Arcanna\'s Deathwand',b:'War Staff'},
    {t:'s',tab:'sets',c:'Arcanna\'s Tricks',n:'Arcanna\'s Sign',b:'Amulet'},
    // ── IRATHA'S FINERY ──
    {t:'s',tab:'sets',c:'Iratha\'s Finery',tier:'Normal',n:'Iratha\'s Coil',b:'Crown'},
    {t:'s',tab:'sets',c:'Iratha\'s Finery',tier:'Normal',n:'Iratha\'s Cord',b:'Heavy Belt'},
    {t:'s',tab:'sets',c:'Iratha\'s Finery',tier:'Normal',n:'Iratha\'s Cuff',b:'Light Gauntlets'},
    {t:'s',tab:'sets',c:'Iratha\'s Finery',n:'Iratha\'s Collar',b:'Amulet'},
    // ── MILABREGA'S REGALIA ──
    {t:'s',tab:'sets',c:'Milabrega\'s Regalia',tier:'Normal',n:'Milabrega\'s Diadem',b:'Crown'},
    {t:'s',tab:'sets',c:'Milabrega\'s Regalia',tier:'Normal',n:'Milabrega\'s Robe',b:'Ancient Armor'},
    {t:'s',tab:'sets',c:'Milabrega\'s Regalia',tier:'Normal',n:'Milabrega\'s Orb',b:'Kite Shield'},
    {t:'s',tab:'sets',c:'Milabrega\'s Regalia',tier:'Normal',n:'Milabrega\'s Rod',b:'War Scepter'},
    // ── TANCRED'S BATTLEGEAR ──
    {t:'s',tab:'sets',c:'Tancred\'s Battlegear',tier:'Normal',n:'Tancred\'s Skull',b:'Bone Helm'},
    {t:'s',tab:'sets',c:'Tancred\'s Battlegear',tier:'Normal',n:'Tancred\'s Spine',b:'Full Plate Mail'},
    {t:'s',tab:'sets',c:'Tancred\'s Battlegear',tier:'Normal',n:'Tancred\'s Hobnails',b:'Boots'},
    {t:'s',tab:'sets',c:'Tancred\'s Battlegear',tier:'Normal',n:'Tancred\'s Crowbill',b:'Military Pick'},
    {t:'s',tab:'sets',c:'Tancred\'s Battlegear',n:'Tancred\'s Weird',b:'Amulet'},
    // ── COW KING'S LEATHERS ──
    {t:'s',tab:'sets',c:'Cow King\'s Leathers',tier:'Normal',n:'Cow King\'s Horns',b:'War Hat',src:'Cow'},
    {t:'s',tab:'sets',c:'Cow King\'s Leathers',tier:'Normal',n:'Cow King\'s Hide',b:'Studded Leather',src:'Cow'},
    {t:'s',tab:'sets',c:'Cow King\'s Leathers',tier:'Normal',n:'Cow King\'s Hooves',b:'Heavy Boots',src:'Cow'},
    // ── SANDER'S FOLLY ──
    {t:'s',tab:'sets',c:'Sander\'s Folly',tier:'Normal',n:'Sander\'s Paragon',b:'Cap'},
    {t:'s',tab:'sets',c:'Sander\'s Folly',tier:'Normal',n:'Sander\'s Riprap',b:'Heavy Boots'},
    {t:'s',tab:'sets',c:'Sander\'s Folly',tier:'Normal',n:'Sander\'s Taboo',b:'Heavy Gloves'},
    {t:'s',tab:'sets',c:'Sander\'s Folly',tier:'Normal',n:'Sander\'s Superstition',b:'Bone Wand'},
    // ── HWANIN'S MAJESTY ──
    {t:'s',tab:'sets',c:'Hwanin\'s Majesty',tier:'Exceptional',n:'Hwanin\'s Splendor',b:'Grand Crown'},
    {t:'s',tab:'sets',c:'Hwanin\'s Majesty',tier:'Exceptional',n:'Hwanin\'s Refuge',b:'Tigulated Mail'},
    {t:'s',tab:'sets',c:'Hwanin\'s Majesty',tier:'Normal',n:'Hwanin\'s Blessing',b:'Belt'},
    {t:'s',tab:'sets',c:'Hwanin\'s Majesty',tier:'Exceptional',n:'Hwanin\'s Justice',b:'Bill'},
    // ── ORPHAN'S CALL ──
    {t:'s',tab:'sets',c:'Orphan\'s Call',tier:'Exceptional',n:'Guillaume\'s Face',b:'Winged Helm'},
    {t:'s',tab:'sets',c:'Orphan\'s Call',tier:'Exceptional',n:'Wilhelm\'s Pride',b:'Battle Belt'},
    {t:'s',tab:'sets',c:'Orphan\'s Call',tier:'Exceptional',n:'Magnus\' Skin',b:'Sharkskin Gloves'},
    {t:'s',tab:'sets',c:'Orphan\'s Call',tier:'Exceptional',n:'Whitstan\'s Guard',b:'Round Shield'},
    // ── THE DISCIPLE ──
    {t:'s',tab:'sets',c:'The Disciple',tier:'Elite',n:'Dark Adherent',b:'Dusk Shroud'},
    {t:'s',tab:'sets',c:'The Disciple',tier:'Exceptional',n:'Rite of Passage',b:'Demonhide Boots'},
    {t:'s',tab:'sets',c:'The Disciple',tier:'Exceptional',n:'Credendum',b:'Mithril Coil'},
    {t:'s',tab:'sets',c:'The Disciple',tier:'Exceptional',n:'Laying of Hands',b:'Bramble Mitts'},
    {t:'s',tab:'sets',c:'The Disciple',n:'Telling of Beads',b:'Amulet'},
    // ── NAJ'S ANCIENT VESTIGE ──
    {t:'s',tab:'sets',c:'Naj\'s Ancient Vestige',tier:'Exceptional',n:'Naj\'s Circlet',b:'Circlet'},
    {t:'s',tab:'sets',c:'Naj\'s Ancient Vestige',tier:'Exceptional',n:'Naj\'s Light Plate',b:'Hellforge Plate'},
    {t:'s',tab:'sets',c:'Naj\'s Ancient Vestige',tier:'Exceptional',n:'Naj\'s Puzzler',b:'Elder Staff'},
    // ── SAZABI'S GRAND TRIBUTE ──
    {t:'s',tab:'sets',c:'Sazabi\'s Grand Tribute',tier:'Exceptional',n:'Sazabi\'s Mental Sheath',b:'Basinet'},
    {t:'s',tab:'sets',c:'Sazabi\'s Grand Tribute',tier:'Exceptional',n:'Sazabi\'s Ghost Liberator',b:'Balrog Skin'},
    {t:'s',tab:'sets',c:'Sazabi\'s Grand Tribute',tier:'Exceptional',n:'Sazabi\'s Cobalt Redeemer',b:'Cryptic Sword'},
    // ── HEAVEN'S BRETHREN ──
    {t:'s',tab:'sets',c:'Heaven\'s Brethren',tier:'Exceptional',n:'Ondal\'s Almighty',b:'Spired Helm'},
    {t:'s',tab:'sets',c:'Heaven\'s Brethren',tier:'Exceptional',n:'Haemosu\'s Adamant',b:'Cuirass'},
    {t:'s',tab:'sets',c:'Heaven\'s Brethren',tier:'Exceptional',n:'Taebaek\'s Glory',b:'Ward'},
    {t:'s',tab:'sets',c:'Heaven\'s Brethren',tier:'Exceptional',n:'Dangoon\'s Teaching',b:'Reinforced Mace'},
    // ── BUL-KATHOS' CHILDREN ──
    {t:'s',tab:'sets',c:'Bul-Kathos\' Children',n:'Bul-Kathos\' Death Band',b:'Ring'},
    {t:'s',tab:'sets',c:'Bul-Kathos\' Children',tier:'Elite',n:'Bul-Kathos\' Tribal Guardian',b:'Colossus Sword'},
    {t:'s',tab:'sets',c:'Bul-Kathos\' Children',tier:'Elite',n:'Bul-Kathos\' Sacred Charge',b:'Colossus Blade'},
    // ── ALDUR'S WATCHTOWER ──
    {t:'s',tab:'sets',c:'Aldur\'s Watchtower',tier:'Elite',n:'Aldur\'s Stony Gaze',b:'Hunter\'s Guise'},
    {t:'s',tab:'sets',c:'Aldur\'s Watchtower',tier:'Elite',n:'Aldur\'s Deception',b:'Shadow Plate'},
    {t:'s',tab:'sets',c:'Aldur\'s Watchtower',tier:'Elite',n:'Aldur\'s Advance',b:'Battle Boots'},
    {t:'s',tab:'sets',c:'Aldur\'s Watchtower',tier:'Elite',n:'Aldur\'s Rhythm',b:'Jagged Star'},
    // ── GRISWOLD'S LEGACY ──
    {t:'s',tab:'sets',c:'Griswold\'s Legacy',tier:'Elite',n:'Griswold\'s Valor',b:'Corona'},
    {t:'s',tab:'sets',c:'Griswold\'s Legacy',tier:'Elite',n:'Griswold\'s Heart',b:'Ornate Plate'},
    {t:'s',tab:'sets',c:'Griswold\'s Legacy',tier:'Elite',n:'Griswold\'s Honor',b:'Vortex Shield'},
    {t:'s',tab:'sets',c:'Griswold\'s Legacy',tier:'Elite',n:'Griswold\'s Redemption',b:'Caduceus'},
    // ── IMMORTAL KING ──
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Will',b:'Avenger Guard'},
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Soul Cage',b:'Sacred Armor'},
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Pillar',b:'War Boots'},
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Detail',b:'War Belt'},
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Forge',b:'War Gauntlets'},
    {t:'s',tab:'sets',c:'Immortal King',tier:'Elite',n:'Immortal King\'s Stone Crusher',b:'Ogre Maul'},
    // ── M'AVINA'S BATTLE HYMN ──
    {t:'s',tab:'sets',c:'M\'avina\'s Battle Hymn',tier:'Elite',n:'M\'avina\'s True Sight',b:'Diadem'},
    {t:'s',tab:'sets',c:'M\'avina\'s Battle Hymn',tier:'Elite',n:'M\'avina\'s Embrace',b:'Kraken Shell'},
    {t:'s',tab:'sets',c:'M\'avina\'s Battle Hymn',tier:'Elite',n:'M\'avina\'s Tenet',b:'Sharkskin Belt'},
    {t:'s',tab:'sets',c:'M\'avina\'s Battle Hymn',tier:'Elite',n:'M\'avina\'s Icy Clutch',b:'Battle Gauntlets'},
    {t:'s',tab:'sets',c:'M\'avina\'s Battle Hymn',tier:'Elite',n:'M\'avina\'s Caster',b:'Grand Matron Bow'},
    // ── NATALYA'S ODIUM ──
    {t:'s',tab:'sets',c:'Natalya\'s Odium',tier:'Elite',n:'Natalya\'s Totem',b:'Grim Helm'},
    {t:'s',tab:'sets',c:'Natalya\'s Odium',tier:'Elite',n:'Natalya\'s Shadow',b:'Loricated Mail'},
    {t:'s',tab:'sets',c:'Natalya\'s Odium',tier:'Elite',n:'Natalya\'s Soul',b:'Mesh Boots'},
    {t:'s',tab:'sets',c:'Natalya\'s Odium',tier:'Elite',n:'Natalya\'s Mark',b:'Scissors Suwayyah'},
    // ── TAL RASHA'S WRAPPINGS ──
    {t:'s',tab:'sets',c:'Tal Rasha\'s Wrappings',tier:'Elite',n:'Tal Rasha\'s Horadric Crest',b:'Death Mask'},
    {t:'s',tab:'sets',c:'Tal Rasha\'s Wrappings',tier:'Elite',n:'Tal Rasha\'s Guardianship',b:'Lacquered Plate'},
    {t:'s',tab:'sets',c:'Tal Rasha\'s Wrappings',tier:'Elite',n:'Tal Rasha\'s Fine-Spun Cloth',b:'Mesh Belt'},
    {t:'s',tab:'sets',c:'Tal Rasha\'s Wrappings',tier:'Elite',n:'Tal Rasha\'s Lidless Eye',b:'Swirling Crystal'},
    {t:'s',tab:'sets',c:'Tal Rasha\'s Wrappings',n:'Tal Rasha\'s Adjudication',b:'Amulet'},
    // ── TRANG-OUL'S AVATAR ──
    {t:'s',tab:'sets',c:'Trang-Oul\'s Avatar',tier:'Elite',n:'Trang-Oul\'s Guise',b:'Bone Visage'},
    {t:'s',tab:'sets',c:'Trang-Oul\'s Avatar',tier:'Elite',n:'Trang-Oul\'s Scales',b:'Chaos Armor'},
    {t:'s',tab:'sets',c:'Trang-Oul\'s Avatar',tier:'Elite',n:'Trang-Oul\'s Girth',b:'Troll Belt'},
    {t:'s',tab:'sets',c:'Trang-Oul\'s Avatar',tier:'Elite',n:'Trang-Oul\'s Claws',b:'Heavy Bracers'},
    {t:'s',tab:'sets',c:'Trang-Oul\'s Avatar',tier:'Elite',n:'Trang-Oul\'s Wing',b:'Cantor Trophy'},
  // #endregion,

  // #region RUNEWORDS
  // ── Helms ──
    {t:'w', tab:'runewords', c:'Helms', n:'Nadir',            b:'2-Socket Helms',           runes:'Nef - Tir'},
    {t:'w', tab:'runewords', c:'Helms', n:'Radiance',         b:'3-Socket Helms',           runes:'Nef - Sol - Ith'},
    {t:'w', tab:'runewords', c:'Helms', n:'Lore',             b:'2-Socket Helms',           runes:'Ort - Sol'},
    {t:'w', tab:'runewords', c:'Helms', n:'Wisdom',           b:'3-Socket Helms',           runes:'Pul - Ith - Eld'},
    {t:'w', tab:'runewords', c:'Helms', n:'Delirium',         b:'3-Socket Helms',           runes:'Lem - Ist - Io'},
    {t:'w', tab:'runewords', c:'Helms', n:'Flickering Flame', b:'3-Socket Helms',           runes:'Nef - Pul - Vex'},
    {t:'w', tab:'runewords', c:'Helms', n:'Dream',            b:'3-Socket Helms',           runes:'Io - Jah - Pul'},
    {t:'w', tab:'runewords', c:'Helms', n:'Ferocity',         b:'3-Socket Helms',           runes:'Zod - Cham - Shael'},
    // ── Chests ──
    {t:'w', tab:'runewords', c:'Chests', n:'Stealth',         b:'2-Socket Chests',          runes:'Tal - Eth'},
    {t:'w', tab:'runewords', c:'Chests', n:'Myth',            b:'3-Socket Chests',          runes:'Hel - Amn - Nef'},
    {t:'w', tab:'runewords', c:'Chests', n:'Peace',           b:'3-Socket Chests',          runes:'Shael - Thul - Amn'},
    {t:'w', tab:'runewords', c:'Chests', n:'Smoke',           b:'2-Socket Chests',          runes:'Nef - Lum'},
    {t:'w', tab:'runewords', c:'Chests', n:'Hustle',          b:'3-Socket Chests',          runes:'Shael - Ko - Eld'},
    {t:'w', tab:'runewords', c:'Chests', n:'Lionheart',       b:'3-Socket Chests',          runes:'Hel - Lum - Fal'},
    {t:'w', tab:'runewords', c:'Chests', n:'Treachery',       b:'3-Socket Chests',          runes:'Shael - Thul - Lem'},
    {t:'w', tab:'runewords', c:'Chests', n:'Wealth',          b:'3-Socket Chests',          runes:'Lem - Ko - Tir'},
    {t:'w', tab:'runewords', c:'Chests', n:'Enlightenment',   b:'3-Socket Chests',          runes:'Pul - Ral - Sol'},
    {t:'w', tab:'runewords', c:'Chests', n:'Duress',          b:'3-Socket Chests',          runes:'Shael - Um - Thul'},
    {t:'w', tab:'runewords', c:'Chests', n:'Stone',           b:'4-Socket Chests',          runes:'Shael - Um - Pul - Lum'},
    {t:'w', tab:'runewords', c:'Chests', n:'Gloom',           b:'3-Socket Chests',          runes:'Fal - Um - Pul'},
    {t:'w', tab:'runewords', c:'Chests', n:'Bone',            b:'3-Socket Chests',          runes:'Sol - Um - Um'},
    {t:'w', tab:'runewords', c:'Chests', n:'Prudence',        b:'2-Socket Chests',          runes:'Mal - Tir'},
    {t:'w', tab:'runewords', c:'Chests', n:'Rain',            b:'3-Socket Chests',          runes:'Ort - Mal - Ith'},
    {t:'w', tab:'runewords', c:'Chests', n:'Principle',       b:'3-Socket Chests',          runes:'Ral - Gul - Eld'},
    {t:'w', tab:'runewords', c:'Chests', n:'Fortitude',       b:'4-Socket Chests',          runes:'El - Sol - Dol - Lo'},
    {t:'w', tab:'runewords', c:'Chests', n:'Bramble',         b:'4-Socket Chests',          runes:'Ral - Ohm - Sur - Eth'},
    {t:'w', tab:'runewords', c:'Chests', n:'Dragon',          b:'3-Socket Chests',          runes:'Sur - Lo - Sol'},
    {t:'w', tab:'runewords', c:'Chests', n:'Chains of Honor', b:'4-Socket Chests',          runes:'Dol - Um - Ber - Ist'},
    {t:'w', tab:'runewords', c:'Chests', n:'Enigma',          b:'3-Socket Chests',          runes:'Jah - Ith - Ber'},
    {t:'w', tab:'runewords', c:'Chests', n:'Innocence',       b:'4-Socket Chests',          runes:'Gul - Lem - Zod - Hel'},
    // ── Shields ──
    {t:'w', tab:'runewords', c:'Shields', n:"Ancients' Pledge",  b:'3-Socket Shields',      runes:'Ral - Ort - Tal'},
    {t:'w', tab:'runewords', c:'Shields', n:'Spirit',            b:'4-Socket Shields',      runes:'Tal - Thul - Ort - Amn'},
    {t:'w', tab:'runewords', c:'Shields', n:'Rhyme',             b:'2-Socket Shields',      runes:'Shael - Eth'},
    {t:'w', tab:'runewords', c:'Shields', n:'Splendor',          b:'2-Socket Shields',      runes:'Eth - Lum'},
    {t:'w', tab:'runewords', c:'Shields', n:'Sanctuary',         b:'3-Socket Shields',      runes:'Ko - Ko - Mal'},
    {t:'w', tab:'runewords', c:'Shields', n:'Exile',             b:'4-Socket Shields',      runes:'Vex - Ohm - Ist - Dol'},
    {t:'w', tab:'runewords', c:'Shields', n:'Epiphany',          b:'4-Socket Shields',      runes:'Lo - Ith - Lo - Ist'},
    {t:'w', tab:'runewords', c:'Shields', n:'Dragon',            b:'3-Socket Shields',      runes:'Sur - Lo - Sol'},
    {t:'w', tab:'runewords', c:'Shields', n:'Dream',             b:'3-Socket Shields',      runes:'Io - Jah - Pul'},
    {t:'w', tab:'runewords', c:'Shields', n:'Phoenix',           b:'4-Socket Shields',      runes:'Vex - Vex - Lo - Jah'},
    {t:'w', tab:'runewords', c:'Shields', n:'Shattered Wall',    b:'4-Socket Paladin Shields', runes:'Zod - Jah - Ral - Cham'},
    // ── Quivers  ──
    {t:'w', tab:'runewords', c:'Quiver', n:"Ancient's Scripture",b:'2-Socket Quivers',     runes:'Tal - Ort'},
    {t:'w', tab:'runewords', c:'Quiver', n:"Ancient's Foresight",b:'2-Socket Quivers',     runes:'Ral - Thul'},
    {t:'w', tab:'runewords', c:'Quiver', n:'Echo',               b:'2-Socket Quivers',      runes:'Sol - Dol'},
    // ── Weapons ──
    {t:'w', tab:'runewords', c:'Weapons', n:'Steel',             b:'2-Socket Swords/Axes/Maces/Claws/Throwing', runes:'Tir - El'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Malice',            b:'3-Socket Melee/Throwing Weapons',           runes:'Ith - El - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Leaf',              b:'2-Socket Staves',                           runes:'Tir - Ral'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Pattern',           b:'3-Socket Claws',                            runes:'Tal - Ort - Tir'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Zephyr',            b:'2-Socket Bows/Crossbows/Throwing',          runes:'Ort - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Holy Thunder',      b:'4-Socket Scepters',                         runes:'Eth - Ral - Ort - Tal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Neophyte',          b:'2-Socket Orbs/Claws/Scepters/Clubs/Staves', runes:'Thul - Tir'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Strength',          b:'2-Socket Melee/Throwing Weapons',           runes:'Amn - Tir'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Edge',              b:'3-Socket Bows/Crossbows',                   runes:'Tir - Tal - Amn'},
    {t:'w', tab:'runewords', c:'Weapons', n:"King's Grace",      b:'3-Socket Scepters/Swords/Claws/Throwing',   runes:'Amn - Ral - Thul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Spirit',            b:'4-Socket Swords/Staves',                    runes:'Tal - Thul - Ort - Amn'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Purity',            b:'3-Socket Polearms/Spears/Staves/Bows',      runes:'Amn - Eth - Thul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Insight',           b:'4-Socket Staves/Polearms/Spears',           runes:'Ral - Tir - Tal - Sol'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Honor',             b:'5-Socket Melee Weapons',                    runes:'Amn - El - Ith - Tir - Sol'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Rampage',           b:'4-Socket Polearms/Spears/Staves',           runes:'Shael - El - Ith - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Echo',              b:'2-Socket Throwing Weapons',                 runes:'Sol - Dol'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Black',             b:'3-Socket Clubs/Hammers/Maces/Claws',        runes:'Thul - Io - Nef'},
    {t:'w', tab:'runewords', c:'Weapons', n:'White',             b:'2-Socket Wands',                            runes:'Dol - Io'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Memory',            b:'4-Socket Staves',                           runes:'Lum - Io - Sol - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Harmony',           b:'4-Socket Bows/Crossbows',                   runes:'Tir - Ith - Sol - Ko'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Melody',            b:'3-Socket Bows/Crossbows',                   runes:'Shael - Ko - Nef'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Unbending Will',    b:'6-Socket Swords',                           runes:'Fal - Io - Ith - Eld - El - Hel'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Obedience',         b:'5-Socket Polearms/Spears/Hammers',          runes:'Hel - Ko - Thul - Eth - Fal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Passion',           b:'4-Socket Weapons',                          runes:'Dol - Ort - Eld - Lem'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Voice of Reason',   b:'4-Socket Swords/Maces/Scepters/Bows',       runes:'Lem - Ko - El - Eld'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Lawbringer',        b:'3-Socket Hammers/Scepters/Swords/Claws',    runes:'Amn - Lem - Ko'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Loyalty',           b:'3-Socket Spears/Bows/Crossbows',            runes:'Pul - Tir - Dol'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Crescent Moon',     b:'3-Socket Axes/Swords/Polearms/Scepters',    runes:'Shael - Um - Tir'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Venom',             b:'3-Socket Weapons',                          runes:'Tal - Dol - Mal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Oath',              b:'4-Socket Swords/Axes/Maces',                runes:'Shael - Pul - Mal - Lum'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Rift',              b:'4-Socket Scepters/Polearms/Spears/Swords',  runes:'Hel - Ko - Lem - Gul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Kingslayer',        b:'4-Socket Swords/Axes',                      runes:'Mal - Um - Gul - Fal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Heart of the Oak',  b:'4-Socket Staves/Maces',                     runes:'Ko - Vex - Pul - Thul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Silence',           b:'6-Socket Weapons',                          runes:'Dol - Eld - Hel - Ist - Tir - Vex'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Death',             b:'5-Socket Swords/Axes',                      runes:'Hel - El - Vex - Ort - Gul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Chaos',             b:'3-Socket Claws',                            runes:'Fal - Ohm - Um'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Call to Arms',      b:'5-Socket Melee Weapons',                    runes:'Amn - Ral - Mal - Ist - Ohm'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Fortitude',         b:'4-Socket Weapons',                          runes:'El - Sol - Dol - Lo'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Grief',             b:'5-Socket Swords/Axes/Polearms',             runes:'Eth - Tir - Lo - Mal - Ral'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Wind',              b:'2-Socket Melee/Throwing Weapons',           runes:'Sur - El'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Wrath',             b:'4-Socket Bows/Crossbows',                   runes:'Pul - Lum - Ber - Mal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Beast',             b:'5-Socket Axes/Scepters/Hammers/Staves',     runes:'Ber - Tir - Um - Mal - Lum'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Eternity',          b:'5-Socket Melee Weapons',                    runes:'Amn - Ber - Ist - Sol - Sur'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Infinity',          b:'4-Socket Polearms/Spears/Staves',           runes:'Ber - Mal - Ber - Ist'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Fury',              b:'3-Socket Melee/Throwing Weapons',           runes:'Jah - Gul - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Famine',            b:'4-Socket Axes/Hammers/Swords',              runes:'Fal - Ohm - Ort - Jah'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Faith',             b:'4-Socket Bows/Crossbows',                   runes:'Ohm - Jah - Lem - Eld'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Ice',               b:'4-Socket Bows/Crossbows',                   runes:'Amn - Shael - Jah - Lo'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Brand',             b:'4-Socket Bows/Crossbows',                   runes:'Jah - Lo - Mal - Gul'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Phoenix',           b:'4-Socket Weapons',                          runes:'Vex - Vex - Lo - Jah'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Destruction',       b:'5-Socket Swords/Polearms/Spears/Staves',    runes:'Vex - Lo - Ber - Jah - Ko'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Last Wish',         b:'6-Socket Axes/Hammers/Swords/Staves',       runes:'Jah - Mal - Jah - Sur - Jah - Ber'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Rapture',           b:'6-Socket Hammers',                          runes:'Vex - Jah - Lo - Ral - Ko - Mal'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Plague',            b:'3-Socket Weapons',                          runes:'Cham - Fal - Um'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Mist',              b:'5-Socket Bows/Crossbows',                   runes:'Cham - Shael - Gul - Thul - Ith'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Dominion',          b:'2-Socket Wands',                            runes:'Cham - Ohm'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Doom',              b:'5-Socket Axes/Hammers/Polearms/Spears',     runes:'Hel - Ohm - Um - Lo - Cham'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Hand of Justice',   b:'4-Socket Weapons',                          runes:'Sur - Cham - Amn - Lo'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Pride',             b:'4-Socket Polearms/Spears/Staves',           runes:'Cham - Sur - Io - Lo'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Asylum',            b:'6-Socket Hammers/Swords/Polearms/Staves',   runes:'Gul - Cham - Hel - Jah - Dol - Um'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Obsession',         b:'6-Socket Staves',                           runes:'Zod - Ist - Lem - Lum - Io - Nef'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Breath of the Dying',b:'6-Socket Weapons',                         runes:'Vex - Hel - El - Eld - Zod - Eth'},
    {t:'w', tab:'runewords', c:'Weapons', n:'Zenith',            b:'5-Socket Polearms/Spears/Staves/Bows',      runes:'Jah - Zod - Ort - Thul - Ral'},
  // #endregion,

  // #region RUNES
  // ── RUNES ──────────────────────────────────
    {t:'r',tab:'runes',c:'Runes',n:'El Rune',b:'El'},
    {t:'r',tab:'runes',c:'Runes',n:'Eld Rune',b:'Eld'},
    {t:'r',tab:'runes',c:'Runes',n:'Tir Rune',b:'Tir'},
    {t:'r',tab:'runes',c:'Runes',n:'Nef Rune',b:'Nef'},
    {t:'r',tab:'runes',c:'Runes',n:'Eth Rune',b:'Eth'},
    {t:'r',tab:'runes',c:'Runes',n:'Ith Rune',b:'Ith'},
    {t:'r',tab:'runes',c:'Runes',n:'Tal Rune',b:'Tal'},
    {t:'r',tab:'runes',c:'Runes',n:'Ral Rune',b:'Ral'},
    {t:'r',tab:'runes',c:'Runes',n:'Ort Rune',b:'Ort'},
    {t:'r',tab:'runes',c:'Runes',n:'Thul Rune',b:'Thul'},
    {t:'r',tab:'runes',c:'Runes',n:'Amn Rune',b:'Amn'},
    {t:'r',tab:'runes',c:'Runes',n:'Sol Rune',b:'Sol'},
    {t:'r',tab:'runes',c:'Runes',n:'Shael Rune',b:'Shael'},
    {t:'r',tab:'runes',c:'Runes',n:'Dol Rune',b:'Dol'},
    {t:'r',tab:'runes',c:'Runes',n:'Hel Rune',b:'Hel'},
    {t:'r',tab:'runes',c:'Runes',n:'Io Rune',b:'Io'},
    {t:'r',tab:'runes',c:'Runes',n:'Lum Rune',b:'Lum'},
    {t:'r',tab:'runes',c:'Runes',n:'Ko Rune',b:'Ko'},
    {t:'r',tab:'runes',c:'Runes',n:'Fal Rune',b:'Fal'},
    {t:'r',tab:'runes',c:'Runes',n:'Lem Rune',b:'Lem'},
    {t:'r',tab:'runes',c:'Runes',n:'Pul Rune',b:'Pul'},
    {t:'r',tab:'runes',c:'Runes',n:'Um Rune',b:'Um'},
    {t:'r',tab:'runes',c:'Runes',n:'Mal Rune',b:'Mal'},
    {t:'r',tab:'runes',c:'Runes',n:'Ist Rune',b:'Ist'},
    {t:'r',tab:'runes',c:'Runes',n:'Gul Rune',b:'Gul'},
    {t:'r',tab:'runes',c:'Runes',n:'Vex Rune',b:'Vex'},
    {t:'r',tab:'runes',c:'Runes',n:'Ohm Rune',b:'Ohm'},
    {t:'r',tab:'runes',c:'Runes',n:'Lo Rune',b:'Lo'},
    {t:'r',tab:'runes',c:'Runes',n:'Sur Rune',b:'Sur'},
    {t:'r',tab:'runes',c:'Runes',n:'Ber Rune',b:'Ber'},
    {t:'r',tab:'runes',c:'Runes',n:'Jah Rune',b:'Jah'},
    {t:'r',tab:'runes',c:'Runes',n:'Cham Rune',b:'Cham'},
    {t:'r',tab:'runes',c:'Runes',n:'Zod Rune',b:'Zod'},
  // #endregion,

  // #region CHARMS
  // ── CHARMS ──────────────────────────────────
    {t:'u',tab:'runes',c:'Charms',n:'Annihilus',b:'Small Charm',src:'DClone'},
    {t:'u',tab:'runes',c:'Charms',n:'Corrupted Annihilus',b:'Small Charm',src:'Rathma'},
    {t:'u',tab:'runes',c:'Charms',n:'Hellfire Torch',b:'Large Charm',src:'Uber'},
    {t:'u',tab:'runes',c:'Charms',n:'Gheed\'s Fortune',b:'Grand Charm'},
  // #endregion,

  // #region JEWELS
  // ── RAINBOW FACETS ──────────────────────────────────
    {t:'u',tab:'runes',c:'Jewels',n:'Rainbow (Fire)',b:'Jewel'},
    {t:'u',tab:'runes',c:'Jewels',n:'Rainbow (Cold)',b:'Jewel'},
    {t:'u',tab:'runes',c:'Jewels',n:'Rainbow (Lightning)',b:'Jewel'},
    {t:'u',tab:'runes',c:'Jewels',n:'Rainbow (Poison)',b:'Jewel'},
  // #endregion,

  // #region MISC
  // ── MISC ──────────────────────────────────
    {t:'u',tab:'runes',c:'Misc',n:'Demonic Cube',b:'Horadric Cube'},
    {t:'u',tab:'runes',c:'Misc',n:'Tainted Worldstone Shard',b:'Misc',src:'Rathma'},
    {t:'u',tab:'runes',c:'Misc',n:'Horadrim Navigator',b:'Tome'},
    {t:'u',tab:'runes',c:'Misc',n:'Horadrim Almanac',b:'Tome'},
    {t:'u',tab:'runes',c:'Misc',n:'Skeleton Key',b:'Key'},
    {t:'u',tab:'runes',c:'Misc',n:'Vial of Lightsong',b:'Misc'},
    {t:'u',tab:'runes',c:'Misc',n:'Lilith\'s Mirror',b:'Misc'},
    {t:'u',tab:'runes',c:'Misc',n:'Larzuk\'s Puzzlebox',b:'Misc'},
    {t:'u',tab:'runes',c:'Misc',n:'Larzuk\'s Puzzlepiece',b:'Misc'},
    {t:'u',tab:'runes',c:'Misc',n:'Twisted Essence of Suffering',b:'Essence',src:'Andariel/Duriel'},
    {t:'u',tab:'runes',c:'Misc',n:'Charged Essence of Hatred',b:'Essence',src:'Mephisto'},
    {t:'u',tab:'runes',c:'Misc',n:'Burning Essence of Terror',b:'Essence',src:'Diablo'},
    {t:'u',tab:'runes',c:'Misc',n:'Festering Essence of Destruction',b:'Essence',src:'Baal'}
  // #endregion
];
